#!/bin/bash

project_directory=~/projects/threadstreaks
header="filename,last-commit,first-commit"

git -C $project_directory ls-tree --full-tree -r HEAD | awk '{ print $4 "," $3 }' > ./data/closures.csv

filenames=$(cat ./data/closures.csv | awk -F "," '{ print $1 }')
echo "$filenames" | xargs -L 1 git -C $project_directory log --follow --diff-filter=A --find-renames=40% -- | ag ^commit | awk '{ print $2 }' > ./data/first-commits

echo "$({ echo "filenames,last-commit,first-commit" ; paste -d ',' ./data/closures.csv ./data/first-commits ; })" > ./data/closures.csv
