#!/bin/bash

project_directory=~/projects/threadstreaks
closures_header="filename,first-commit,last-commit"
dates_header="commit,date"

filenames=$(git -C $project_directory ls-tree --full-tree -r HEAD | awk '{ print $4 }')

echo "$filenames"> ./data/filenames

echo "$(echo "$filenames" | xargs -L 1 git -C $project_directory log -1 --pretty=format:"%H%n" -- )"> ./data/last-commits

echo "$filenames" | xargs -L 1 git -C $project_directory log --follow --diff-filter=A --find-renames=40% -- | ag ^commit | awk '{ print $2 }' > ./data/first-commits

echo "$({ echo "$closures_header" ; paste -d ',' ./data/filenames ./data/first-commits ./data/last-commits ; })" > ./data/closures.csv

echo "$({ echo "$dates_header" ; git -C $project_directory log --pretty=format:"%H %ci" HEAD | awk '{ print $1 "," $2}' ; })" > ./data/dates.csv
