#!/bin/bash

project_directory=~/projects/threadstreaks
closures_header="filename,first-commit,last-commit"
dates_header="commit,date"
output_directory=./resources/public

filenames=$(git -C $project_directory ls-tree --full-tree -r HEAD | awk '{ print $4 }')

echo "$filenames"> $output_directory/filenames

echo "$(echo "$filenames" | xargs -L 1 git -C $project_directory log -1 --pretty=format:"%H%n" -- )"> $output_directory/last-commits

echo "$filenames" | xargs -L 1 git -C $project_directory log --follow --diff-filter=A --find-renames=40% -- | ag ^commit | awk '{ print $2 }' > $output_directory/first-commits

echo "$({ echo "$closures_header" ; paste -d ',' $output_directory/filenames $output_directory/first-commits $output_directory/last-commits ; })" > $output_directory/closures.csv

echo "$({ echo "$dates_header" ; git -C $project_directory log --pretty=format:"%H %ci" HEAD | awk '{ print $1 "," $2}' ; })" > $output_directory/dates.csv
